### ISSUE TITLE
Windows 10 version

### ISSUE THREAD

**Issue by cmiscloni** [updatengine-ng/updatengine-client#1]
Windows 10 version is not present in the GUI even with the latest version of updatengine client (4.0).

**Comment by noelmartinon** [comment]
Hello,
Do you mean like 1703, 1809, 1909... ?

**Comment by cmiscloni** [comment]
No, like 10.18363 for example

![image](https://user-images.githubusercontent.com/4446733/74587432-7ad9de80-4ff2-11ea-8647-fda593a4750d.png)

**Comment by noelmartinon** [comment]
And what does the "wmic os get version /format:list" command return ?
You should have e.g. "Version=10.0.15063"

**Comment by cmiscloni** [comment]
Yes, Version=10.0.18363
It seems that the client doesn't send the version to the server.
How I can check if client return the version correctly ? 
The -v parameter doesn't return any values in cli, only:

`Just to test, inventory will not be send
2020-02-15-19:38:16
Inventory built`

**Comment by noelmartinon** [comment]
OK. Could you test with that version please : https://github.com/updatengine-ng/updatengine-client/releases/download/4.0.1/updatengine-client-setup-4.0.1.exe

**Comment by cmiscloni** [comment]
No, version is still empty after a new inventory with 4.0.1.

**Comment by noelmartinon** [comment]
And in the shell output with -v option ?

**Comment by cmiscloni** [comment]
`Just to test, inventory will not be send 2020-02-17-22:10:16 Inventory built`

**Comment by cmiscloni** [comment]
It works after a restart, sorry
Thanks
